server:
  port: 8091
spring:
  application:
    name: CloudGateWay
  cloud:
    gateway:
      routes:
      - id: ProductService
        uri: http://localhost:8082/
        predicates:
        - Path=/api/product/**
      - id: OrderService
        uri: http://localhost:8083/
        predicates:
        - Path=/api/order/**
#  profiles:
#    default: dev
    
    
    
    
